%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-py-trees-ros-viewer
Version:        0.2.5
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS py_trees_ros_viewer package

License:        BSD
URL:            https://github.com/splintered-reality/py_trees_ros_viewer
Source0:        %{name}-%{version}.tar.gz

Requires:       libXext-devel
Requires:       pyqtwebengine-devel
Requires:       python3-qt5-devel
Requires:       python3-qt5-webengine
Requires:       python3-sip-devel
Requires:       ros-jazzy-py-trees-js
Requires:       ros-jazzy-py-trees-ros-interfaces
Requires:       ros-jazzy-rclpy
Requires:       ros-jazzy-unique-identifier-msgs
Requires:       ros-jazzy-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  python%{python3_pkgversion}-setuptools
BuildRequires:  python3-qt5-devel
BuildRequires:  qt5-qttools-devel
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A Qt-JS application for visualisation of executing/log-replayed behaviour trees
in a ROS2 ecosystem.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/jazzy"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Mon Jan 13 2025 Daniel Stonier <d.stonier@gmail.com> - 0.2.5-1
- Autogenerated by Bloom

* Mon Jan 13 2025 Daniel Stonier <d.stonier@gmail.com> - 0.2.4-1
- Autogenerated by Bloom

